In [ ]:
import numpy as np


Задача 1

In [ ]:
A = np.array([[1,2,1],
              [-2,1,1]])

B = np.array([[3,1],
              [-1,0],
              [2,4]])

C = np.array([[-2,2],
              [1,-1],
              [1,2]])

In [ ]:
def maxrix_calc(A,B):
  try:
    res1= A+2*B
  except:
    res1 = 'Матрицу имеют разную размерность'
  finally:
    print(res1)


In [ ]:
maxrix_calc(A,B)

Матрицу имеют разную размерность


In [ ]:
maxrix_calc(B,C)

[[-1  5]
 [ 1 -2]
 [ 4  8]]


Задача 2

In [ ]:
A = []
line = np.zeros(8)
for i in range(8):
  A.append(line)
B =np.array(A)


value = 0
for i in range(len(B)):
  value+=1
  for j in range(len(B[i])):
    if value >= 1:
      value-=1
      B[i][j] = value
    else:
      value+=1
      B[i][j] = value
print(B)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Задача **3**

In [ ]:
vec1 = np.linspace(0.0,1.4,15)
vec2 = np.linspace(1,6,6)

A = vec1.reshape(5,3)
B = vec2.reshape(3,2)
print('A=',A)
print('B=',B)
mult = np.dot(A,B)
print('A*B=',mult)


A= [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
B= [[1. 2.]
 [3. 4.]
 [5. 6.]]
A*B= [[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


Задача 4


In [ ]:
A= np.arange(1,37,1)
print(A)

for i in A:
  if i%3 ==0:
    print(i)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
3
6
9
12
15
18
21
24
27
30
33
36
